const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../plugin.js'),'utf8').replace(/^import .*\n/gm,'').replace('export default {','const plugin = {');
let request;
const sandbox={host:{requestProfile:async(...args)=>{request=args;return {config:{model:{default:'main',provider:'openrouter'}}}}},Map};
vm.createContext(sandbox);vm.runInContext(source+'\nthis.parse=parseConfig;this.group=groupModels;this.fetch=fetchModels;',sandbox);
const config={model:{default:'main',provider:'openrouter'},api_key:'do-not-retain',auxiliary:{title:{provider:'auto'},vision:{model:'image',provider:'custom',enabled:false}},delegation:{},fallback_providers:[{model:'backup',provider:'other'}],moa:{enabled:false,default_preset:'test',presets:{test:{reference_models:['ref'],aggregator:'agg'}}}};
const data=sandbox.parse(config);
assert.equal(data.main.model,'main');assert.equal(data.routes.find(r=>r.key==='aux:title').model,'main');
assert.equal(data.routes.find(r=>r.key==='aux:title').provider,'openrouter');
assert.equal(data.routes.find(r=>r.key==='aux:vision').enabled,false);
assert.equal(data.routes.find(r=>r.key==='worker').model,'main');
assert.equal(data.routes.find(r=>r.key==='worker').fallbacks[0].model,'backup');
assert.equal(data.routes.find(r=>r.key==='moa:test:ref:0').enabled,false);
assert.doesNotMatch(JSON.stringify(data),/do-not-retain|api_key/);
assert.equal(sandbox.group(data).filter(r=>r.model==='main').length,1);
assert.throws(()=>sandbox.parse(null),/Invalid/);
assert.equal(sandbox.parse({model:'simple'}).main.model,'simple');
(async()=>{await sandbox.fetch({profile:'example',connectionId:'local'});assert.equal(request[0].targetProfile,'example');assert.equal(request[1],'config.get');assert.equal(request[2].profile,'example');
 sandbox.host.requestProfile=undefined;sandbox.host.request=async(...args)=>{request=args;return {model:'fallback'}};
 assert.equal((await sandbox.fetch({profile:'example'})).main.model,'fallback');assert.equal(request[1].profile,'example');
 console.log('Profile Models checks passed: inherited routes, disabled MoA, fallbacks, grouping, credential filtering and profile-scoped requests.');
})().catch(err=>{console.error(err);process.exitCode=1});
